version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/../jenkins_home:/var/jenkins_home
    networks:
      - net
  remotehost:
    container_name: remotehost
    image: remotehost
    build:
      context: remotehost
    networks:
      - net
networks:
  net:
